name: flutter_cupertino_date_picker_fork
description: Flutter cupertino date picker. Display DatePicker in iOS style. Support both Android and iOS platform.
version: 1.0.2
homepage: https://github.com/shareven/flutter_cupertino_date_picker_fork

dependencies:
  flutter:
    sdk: flutter

flutter:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"
